//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Export.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        public int MusteriID { get; set; }
        public Nullable<int> SevkiyatID { get; set; }
        public string MusteriAdSoyad { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public string OdemeDurum { get; set; }
    }
}
